Module11 task1
htmlacademy-javascript/1626911-kekstagram-25 pull request #13
Opened 2022-04-09 15:22 UTC by kirill-nef

2022-04-10 07:47 UTC, KletskovG requested changes
Есть моменты, которые стоит улучшить

2022-04-10 07:47 UTC, KletskovG commented on js/api.js
> +    .catch(() => {
Лучше поменять `catch` и `then` местами. Сначала рассматриваем благоприятный сценарий, и только в случае ошибки делаем какие-то нестандартные обработки 

Давай поместим catch в конец, пожалуйста

2022-04-10 07:47 UTC, KletskovG commented on js/api.js
> +        onFail('Фотография успешно отправлена!', 6000);
Тебе не кажется странным, что в случае успеха мы вызываем функцию с названием "при неудаче"?)

Нужно либо поменять название у второго аргумента с `onFail` на что то другое 

Либо не вызывать его в `then`, а использовать какой-нибудь `showAlert`

2022-04-10 07:47 UTC, KletskovG commented on js/renderingThumbnails.js
> +function renderingThumbnails (arrayPicture) {
Лучше назвать `renderThumbnails`. "Отрисовать"

2022-04-11 03:46 UTC, kirill-nef commented on js/api.js
> +    .catch(() => {
Исправил

2022-04-11 03:48 UTC, kirill-nef commented on js/api.js
> +        onFail('Фотография успешно отправлена!', 6000);
Исправил только название)

2022-04-11 03:50 UTC, kirill-nef commented on js/renderingThumbnails.js
> +function renderingThumbnails (arrayPicture) {
исправил!

2022-04-11 07:27 UTC, merged