ДЗ modul7task2
htmlacademy-javascript/1626911-kekstagram-25 pull request #6
Opened 2022-03-16 05:08 UTC by kirill-nef

2022-03-16 16:13 UTC, KletskovG requested changes
Есть небольшие моменты, которые можно улучшить

2022-03-16 16:13 UTC, KletskovG commented on js/commentList.js
> +  taskCommentsText.textContent = (createDataUsers[numberComment].comment);
А зачем тут `(createDataUsers[numberComment].comment);`

Можно ведь просто 
`(createDataUsers[numberComment].comment);`

2022-03-16 16:13 UTC, KletskovG commented on js/openBigPicture.js
> +const body = document.querySelector('body');
Тут можно просто `document.body`

2022-03-16 16:13 UTC, KletskovG commented on js/openBigPicture.js
> +const openBigPicture = function (numberPicture) {
Предлагаю назвать параметр этой функции по-другому, так как сейчас он написал с ошибкой (В плане в реальной речи нельзя так сказать))

Давай используем, например, `pictureIndex` - чисто с точки зрения человеческой речи он намного более точно отображает смысл

2022-03-16 16:13 UTC, KletskovG commented on js/openBigPicture.js
> +const bigPictureSrc = bigPicture.querySelector('img');
Тут название стоит заменить, можно просто взять `bigPictureImage`, получается небольшая тавтология, но на самом деле это намного лучше, чем то, что дальше у тебя написано `bigPictureSrc.src` - это уже прям явное дублирование, что не очень хорошо и может путать

2022-03-17 04:10 UTC, kirill-nef commented on js/openBigPicture.js
> +const body = document.querySelector('body');
Исправил!

2022-03-17 04:29 UTC, kirill-nef commented on js/openBigPicture.js
> +const openBigPicture = function (numberPicture) {
Исправил!

2022-03-17 08:04 UTC, kirill-nef commented on js/commentList.js
> +  taskCommentsText.textContent = (createDataUsers[numberComment].comment);
Исправил

2022-03-17 20:28 UTC, merged